[phases.setup]
nixPkgs = { 
  python = "3.12",
  ffmpeg = "6.1",
  pkg-config = "0.29.2"
}

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "PYTHONPATH=backend uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --workers 1"

